# Generated by Django 4.0.2 on 2022-02-22 09:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='patientdetails',
            name='tabletsStatus',
            field=models.CharField(blank=True, max_length=15, null=True),
        ),
        migrations.CreateModel(
            name='notAvailableTablets',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tabletsname', models.CharField(blank=True, max_length=70, null=True)),
                ('patientnum', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='users.patientdetails')),
            ],
        ),
    ]
