# Generated by Django 4.0.2 on 2022-02-24 04:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_delete_usersession'),
    ]

    operations = [
        migrations.AddField(
            model_name='patientdetails',
            name='generalReason',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
